"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

def main():
    print(sumOfEvenFibonacciNumbers(100)) # 44
    print(sumOfEvenFibonacciNumbers(4_000_000))

def sumOfEvenFibonacciNumbers(limit):
    return sum(filter(isEven, fibonaccis(limit)))

def isEven(n):
    return n % 2 == 0

# oeis.org/A000045
def fibonaccis(limit):
    ns = [0,1]

    while True:
        n = ns[-2] + ns[-1]

        if n <= limit:
            ns.append(n)
        else:
            break

    return ns

main()
