"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

import extra

import itertools

def main():
    for i in [100, 4_000_000]:
        print(sumOfEvenFibonacciNumbers(i))
        # 44
        # 4_613_732

def sumOfEvenFibonacciNumbers(limit):
    return sum(filter(extra.isEven, itertools.takewhile(lambda n: n <= limit, extra.fibonaccis())))

main()
